import { Datatest } from './datatest';

export const DATATEST: Datatest[] = [
  {id: 1,
    name : "Juan Perez",
    btn_edit : "EDITAR PERFIL",
    btn_gestion : "Gestión",
    btn_online :"Tienda online",
    btn_ventas : "Ventas",
    btn_mark : "Marketing",
    btn_soport : "Soporte",
    title_1 : "Su empresa en Testa",
    empresa_name : "Sarasa",
    title_2 : "Su nombre en testa Gestión aparece en las notificacione por correo electrónico.\
    Su nombre en testa Gestión no afecta a la URL  de su sistema, que siempre es",
    mail_empresa : "https://sarasa44643423.testa.com",
    title_3 : "Su empresa en Testa",
    title_4 : "Su subdominio actual:",
    dominio : "sarasa44643423.testa.com",
    subdominio : "Cambiar subdominio",
    t_invoice : "Estado de facturación",
    t1_invoice : "AL DÍA",
    ct1_invoice : "statusf",
    t2_invoice : "Última factura",
    btn_all_invoice : "VER TODAS LAS FACTURAS",
    date_invoice_t : "Fecha de emisión",
    date_invoice : "10/04/2018",
    date_num_invoice_t : "Número de factura",
    num_invoice : "6516-19225046",
    date_expire_t : "Fecha de vencimiento",
    date_expire : "26/04/2018",
    importe_t : "Importe",
    importe : "$547,50",
    btc_down_invoice :"Descargar",
    mostrar: true,
    btn_comprar:false
},
{id: 2,
    name : "Omar Orozco",
    btn_edit : "EDITAR PERFIL",
    btn_gestion : "Gestión",
    btn_online :"Tienda online",
    btn_ventas : "Ventas",
    btn_mark : "Marketing",
    btn_soport : "Soporte",
    title_1 : "Su empresa en Testa",
    empresa_name : "Sarasa",
    title_2 : "Su nombre en testa Gestión aparece en las notificacione por correo electrónico.\
    Su nombre en testa Gestión no afecta a la URL  de su sistema, que siempre es",
    mail_empresa : "https://sarasa44643423.testa.com",
    title_3 : "Su empresa en Testa",
    title_4 : "Su subdominio actual:",
    dominio : "sarasa44643423.testa.com",
    subdominio : "Cambiar subdominio",
    t_invoice : "Estado de facturación",
    t1_invoice : "VENCIDA",
    ct1_invoice : "statusfv",
    t2_invoice : "Última factura",
    btn_all_invoice : "VER TODAS LAS FACTURAS",
    date_invoice_t : "Fecha de emisión",
    date_invoice : "10/04/2018",
    date_num_invoice_t : "Número de factura",
    num_invoice : "6516-19225046",
    date_expire_t : "Fecha de vencimiento",
    date_expire : "26/04/2018",
    importe_t : "Importe",
    importe : "$547,50",
    btc_down_invoice :"Descargar",
    mostrar: true,
    btn_comprar:false
},
{id: 3,
    name : "Manuel Avila",
    btn_edit : "EDITAR PERFIL",
    btn_gestion : "Gestión",
    btn_online :"Tienda online",
    btn_ventas : "Ventas",
    btn_mark : "Marketing",
    btn_soport : "Soporte",
    title_1 : "Su empresa en Testa",
    empresa_name : "Sarasa",
    title_2 : "Su nombre en testa Gestión aparece en las notificacione por correo electrónico.\
    Su nombre en testa Gestión no afecta a la URL  de su sistema, que siempre es",
    mail_empresa : "https://sarasa44643423.testa.com",
    title_3 : "Su empresa en Testa",
    title_4 : "Su subdominio actual:",
    dominio : "sarasa44643423.testa.com",
    subdominio : "Cambiar subdominio",
    t_invoice : "Estado de facturación",
    t1_invoice : "Quedan 13 días de prueba",
    ct1_invoice : "statusfv",
    t2_invoice : "Última factura",
    btn_all_invoice : "VER TODAS LAS FACTURAS",
    date_invoice_t : "Fecha de emisión",
    date_invoice : "10/04/2018",
    date_num_invoice_t : "Número de factura",
    num_invoice : "6516-19225046",
    date_expire_t : "Fecha de vencimiento",
    date_expire : "26/04/2018",
    importe_t : "Importe",
    importe : "$547,50",
    btc_down_invoice :"Descargar",
    mostrar: false,
    btn_comprar:true
},
{id: 4,
    name : "Omar Orozco",
    btn_edit : "EDITAR PERFIL",
    btn_gestion : "Gestión",
    btn_online :"Tienda online",
    btn_ventas : "Ventas",
    btn_mark : "Marketing",
    btn_soport : "Soporte",
    title_1 : "Su empresa en Testa",
    empresa_name : "Sarasa",
    title_2 : "Su nombre en testa Gestión aparece en las notificacione por correo electrónico.\
    Su nombre en testa Gestión no afecta a la URL  de su sistema, que siempre es",
    mail_empresa : "https://sarasa44643423.testa.com",
    title_3 : "Su empresa en Testa",
    title_4 : "Su subdominio actual:",
    dominio : "sarasa44643423.testa.com",
    subdominio : "Cambiar subdominio",
    t_invoice : "Estado de facturación",
    t1_invoice : "VENCIDA",
    ct1_invoice : "statusfv",
    t2_invoice : "Última factura",
    btn_all_invoice : "VER TODAS LAS FACTURAS",
    date_invoice_t : "Fecha de emisión",
    date_invoice : "10/04/2018",
    date_num_invoice_t : "Número de factura",
    num_invoice : "6516-19225046",
    date_expire_t : "Fecha de vencimiento",
    date_expire : "26/04/2018",
    importe_t : "Importe",
    importe : "$547,50",
    btc_down_invoice :"Descargar",
    mostrar: true,
    btn_comprar:false
},
{id: 5,
    name : "Omar Orozco",
    btn_edit : "EDITAR PERFIL",
    btn_gestion : "Gestión",
    btn_online :"Tienda online",
    btn_ventas : "Ventas",
    btn_mark : "Marketing",
    btn_soport : "Soporte",
    title_1 : "Su empresa en Testa",
    empresa_name : "Sarasa",
    title_2 : "Su nombre en testa Gestión aparece en las notificacione por correo electrónico.\
    Su nombre en testa Gestión no afecta a la URL  de su sistema, que siempre es",
    mail_empresa : "https://sarasa44643423.testa.com",
    title_3 : "Su empresa en Testa",
    title_4 : "Su subdominio actual:",
    dominio : "sarasa44643423.testa.com",
    subdominio : "Cambiar subdominio",
    t_invoice : "Estado de facturación",
    t1_invoice : "VENCIDA",
    ct1_invoice : "statusfv",
    t2_invoice : "Última factura",
    btn_all_invoice : "VER TODAS LAS FACTURAS",
    date_invoice_t : "Fecha de emisión",
    date_invoice : "10/04/2018",
    date_num_invoice_t : "Número de factura",
    num_invoice : "6516-19225046",
    date_expire_t : "Fecha de vencimiento",
    date_expire : "26/04/2018",
    importe_t : "Importe",
    importe : "$547,50",
    btc_down_invoice :"Descargar",
    mostrar: true,
    btn_comprar:false
},

];
